# Generated by Django 2.0.7 on 2019-07-23 08:43

import datetime
import django.core.validators
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DateOfLeave',
            fields=[
                ('date_of_leave', models.DateField(primary_key=True, serialize=False, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Department',
            fields=[
                ('department', models.CharField(max_length=50, primary_key=True, serialize=False, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Email',
            fields=[
                ('email', models.EmailField(max_length=100, primary_key=True, serialize=False, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='EmployeeName',
            fields=[
                ('employee_name', models.CharField(max_length=100, primary_key=True, serialize=False, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='EmployeeStatus',
            fields=[
                ('employee_status', models.CharField(max_length=10, primary_key=True, serialize=False, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='LeaveDays',
            fields=[
                ('leave_days', models.IntegerField(primary_key=True, serialize=False, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='LeaveForm',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('employee_name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=70, unique=True)),
                ('department', models.CharField(max_length=20)),
                ('line_supervisor', models.CharField(max_length=20)),
                ('user_type', models.CharField(choices=[('User', 'User'), ('Manager', 'Manager'), ('HR', 'HR'), ('Admin', 'Admin')], default='User', max_length=20)),
                ('leave_days', models.PositiveIntegerField(default=21, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(21)])),
                ('type_of_leave', models.CharField(choices=[('SICK', 'sick'), ('ANNUAL_LEAVE', 'Annual-Leave'), ('BEREAVEMENT', 'Bereavement'), ('PERSONAL_LEAVE', 'Personal-Leave'), ('MATERNITY_OR_PATERNITY', 'Maternity/Paternity'), ('STUDY_LEAVE', 'Study-Leave')], default='SICK', max_length=50)),
                ('date_of_leave', models.DateTimeField(default=datetime.datetime(2019, 7, 23, 8, 43, 54, 750680, tzinfo=utc))),
                ('leave_from', models.DateField()),
                ('leave_to', models.DateField()),
                ('return_date', models.DateField()),
                ('no_of_days', models.IntegerField()),
                ('employee_status', models.CharField(choices=[('Onleave', 'Onleave'), ('Working', 'Working')], default='Active', max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='LeaveFrom',
            fields=[
                ('leave_from', models.DateField(primary_key=True, serialize=False, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='LeaveTo',
            fields=[
                ('leave_to', models.DateField(primary_key=True, serialize=False, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='LineSupervisor',
            fields=[
                ('line_supervisor', models.CharField(max_length=20, primary_key=True, serialize=False, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='NumberOfDays',
            fields=[
                ('no_of_days', models.IntegerField(primary_key=True, serialize=False, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='ReturnDate',
            fields=[
                ('return_date', models.DateField(primary_key=True, serialize=False, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='TypeOfLeave',
            fields=[
                ('type_of_leave', models.CharField(max_length=2, primary_key=True, serialize=False, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='UserType',
            fields=[
                ('user_type', models.CharField(max_length=20, primary_key=True, serialize=False, unique=True)),
            ],
        ),
    ]
