# Generated by Django 2.0.7 on 2019-07-23 08:54

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='leaveform',
            name='date_of_leave',
            field=models.DateTimeField(default=datetime.datetime(2019, 7, 23, 8, 54, 58, 503745, tzinfo=utc)),
        ),
    ]
