# Generated by Django 2.1.5 on 2019-07-25 08:44

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0002_auto_20190723_1154'),
    ]

    operations = [
        migrations.AlterField(
            model_name='leaveform',
            name='date_of_leave',
            field=models.DateTimeField(default=datetime.datetime(2019, 7, 25, 8, 44, 11, 283609, tzinfo=utc)),
        ),
    ]
