# Generated by Django 2.1.5 on 2019-07-25 08:44

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DateOfLeave',
            fields=[
                ('date_of_leave', models.DateField(primary_key=True, serialize=False, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Department',
            fields=[
                ('department', models.CharField(max_length=50, primary_key=True, serialize=False, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Email',
            fields=[
                ('email', models.EmailField(max_length=100, primary_key=True, serialize=False, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='EmployeeName',
            fields=[
                ('employee_name', models.CharField(max_length=100, primary_key=True, serialize=False, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='FinancialYear',
            fields=[
                ('financial_year', models.IntegerField(primary_key=True, serialize=False)),
                ('set_current', models.CharField(choices=[('YES', 'YES'), ('NO', 'NO')], max_length=3)),
            ],
        ),
        migrations.CreateModel(
            name='LeaveApplication',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('employee_name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=70, unique=True)),
                ('department', models.CharField(max_length=20)),
                ('type_of_leave', models.CharField(max_length=50)),
                ('leave_days', models.IntegerField(default=0)),
                ('other_reason', models.CharField(max_length=100)),
                ('financial_year', models.IntegerField(choices=[('2018', '2018'), ('2019', '2019')], default=2018)),
                ('date_of_leave', models.DateTimeField(default=datetime.datetime(2019, 7, 25, 11, 44, 11, 299234))),
                ('leave_from', models.DateField()),
                ('leave_to', models.DateField()),
                ('return_date', models.DateField()),
                ('no_of_days', models.IntegerField()),
                ('line_supervisor_name', models.CharField(max_length=20)),
                ('line_supervisor_email', models.CharField(max_length=20)),
                ('leave_status', models.CharField(choices=[('Approved', 'Approved'), ('Pending', 'Pending'), ('Rejected', 'Rejected')], max_length=50)),
                ('approve_category', models.CharField(choices=[('Approve', 'Approve'), ('Reject', 'Reject')], max_length=50)),
                ('line_supervisor_remarks', models.CharField(blank=True, help_text='Maximum Limit is 200 Characters', max_length=200, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='LeaveApplicationDetails',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('employee_name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=70, unique=True)),
                ('department', models.CharField(max_length=20)),
                ('type_of_leave', models.CharField(max_length=50)),
                ('leave_month', models.DateField()),
                ('leave_days', models.IntegerField(default=0)),
                ('other_reason', models.CharField(max_length=100)),
                ('financial_year', models.IntegerField(choices=[('2018', '2018'), ('2019', '2019')], default=2018)),
                ('date_of_leave', models.DateTimeField(default=datetime.datetime(2019, 7, 25, 11, 44, 11, 299234))),
                ('leave_from', models.DateField()),
                ('leave_to', models.DateField()),
                ('return_date', models.DateField()),
                ('no_of_days', models.IntegerField()),
                ('line_supervisor_name', models.CharField(max_length=20)),
                ('line_supervisor_email', models.CharField(max_length=20)),
                ('leave_status', models.CharField(choices=[('Approved', 'Approved'), ('Pending', 'Pending'), ('Rejected', 'Rejected')], max_length=50)),
                ('approve_category', models.CharField(choices=[('Approve', 'Approve'), ('Reject', 'Reject')], max_length=50)),
                ('line_supervisor_remarks', models.CharField(blank=True, help_text='Maximum Limit is 200 Characters', max_length=200, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='LeaveDays',
            fields=[
                ('leave_days', models.IntegerField(max_length=20, primary_key=True, serialize=False, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='LeaveFrom',
            fields=[
                ('leave_from', models.DateField(primary_key=True, serialize=False, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='LeaveMonth',
            fields=[
                ('leave_month', models.DateField(primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='LeaveRegister',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=70, unique=True)),
                ('employee_name', models.CharField(max_length=100)),
                ('department', models.CharField(max_length=20)),
                ('financial_year', models.IntegerField(choices=[('2018', '2018'), ('2019', '2019')], default=2018)),
                ('leave_month', models.DateField(blank=True, null=True)),
                ('line_supervisor_name', models.CharField(max_length=20)),
                ('line_supervisor_email', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='LeaveStatus',
            fields=[
                ('leave_status', models.EmailField(max_length=100, primary_key=True, serialize=False, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='LeaveTo',
            fields=[
                ('leave_to', models.DateField(primary_key=True, serialize=False, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='LineSupervisor',
            fields=[
                ('line_supervisor', models.CharField(max_length=20, primary_key=True, serialize=False, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='LineSupervisorEmail',
            fields=[
                ('line_supervisor_email', models.EmailField(max_length=100, primary_key=True, serialize=False, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='NumberOfDays',
            fields=[
                ('no_of_days', models.IntegerField(primary_key=True, serialize=False, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='OtherReason',
            fields=[
                ('other_reason', models.CharField(max_length=100, primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='Remarks',
            fields=[
                ('line_supervisor_remarks', models.EmailField(max_length=100, primary_key=True, serialize=False, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='ReturnDate',
            fields=[
                ('return_date', models.DateField(primary_key=True, serialize=False, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='TypeOfLeave',
            fields=[
                ('type_of_leave', models.CharField(max_length=20, primary_key=True, serialize=False, unique=True)),
            ],
        ),
    ]
